### ISSUE TITLE
make compatible with <0.12

### ISSUE THREAD

**Issue by sevko** [pelias/pelias-cli#4]
The tool uses the `child_process` library's `.execSync()` to simplify a good bit of code, but it was unfortunately only introduced in Node v0.12. Try to implement a 0.10-compatible alternative. See [this PR comment thread](https://github.com/pelias/cli/pull/3) for some relevant discussion.

**Comment by dianashk** [comment]
Water under the bridge. We've moved up to 0.12 and higher at this point.
